parameters:
  restboot.rest.payload.format: 'json'
  restboot.rest.priority.controller: 1
  restboot.rest.payload.accepted.formats: ['json', 'xml']

services:
  _defaults:
    autowire: true
    autoconfigure: true

  SilasYudi\RestBootBundle\Serializer\DefaultFormat:
    arguments:
      - '%restboot.rest.payload.format%'

  SilasYudi\RestBootBundle\Serializer\AcceptedFormats:
    arguments:
      - '%restboot.rest.payload.accepted.formats%'

  SilasYudi\RestBootBundle\Rest\Converter\BodyConverter:
    tags: [ name: 'restboot.rest.converter' ]

  SilasYudi\RestBootBundle\Rest\Converter\QueryConverter:
    tags: [ name: 'restboot.rest.converter' ]

  SilasYudi\RestBootBundle\EventListener\RestListener:
    arguments: [ !tagged_iterator 'restboot.rest.converter' ]
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.controller', method: 'onKernelController', priority: '%restboot.rest.priority.controller%' }
    public: true
