parameters:
  restboot.transaction.priority.controller: 1
  restboot.transaction.priority.response: 1
  restboot.transaction.priority.exception: 1

services:
  _defaults:
    autowire: true
    autoconfigure: true

  SilasYudi\RestBootBundle\EventListener\TransactionListener:
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.controller', method: 'onKernelController', priority: '%restboot.transaction.priority.controller%' }
      - { name: 'kernel.event_listener', event: 'kernel.response', method: 'onKernelResponse', priority: '%restboot.transaction.priority.response%' }
      - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException', priority: '%restboot.transaction.priority.exception%' }
    public: true
